// GENERATED by scripts/build-tokens.mjs from design/tokens.json. Do not edit.
export const P = {
  'sky-100': 0xddeef7,
  'sky-200': 0xbfe1f5,
  'sky-300': 0x7fc1ec,
  'sky-500': 0x4c9edd,
  'sky-700': 0x2e6fb0,
  'dusk-300': 0xf3a25c,
  'dusk-700': 0x5b4a8c,
  'cloud-50': 0xf6f3ea,
  'leaf-200': 0xb8d45a,
  'leaf-400': 0x6daa3f,
  'leaf-600': 0x3f7d2e,
  'leaf-800': 0x245b2a,
  'sea-400': 0x2fb3c8,
  'sea-600': 0x1f8fa8,
  'sun-300': 0xf2a65a,
  'sun-500': 0xe07b39,
  'roof-500': 0xd9744a,
  'wood-600': 0x8b5a2b,
  'vend-500': 0xc8322b,
  'sand-200': 0xe8dcc0,
  'sand-300': 0xd8c9a3,
  'stone-400': 0xb9b3a6,
  'stone-600': 0x8c8677,
  'shade-600': 0x4a4e7a,
  'shade-800': 0x2e3153,
  'paper-50': 0xfbf7ec,
  'paper-100': 0xf4ecd8,
  'paper-200': 0xe9dec3,
  'ink-900': 0x2b2a33,
  'ink-700': 0x4a4852,
  'ink-500': 0x6e6b78,
  'ochre-500': 0xc9963b,
  'skin-300': 0xf1c9a5,
  'hair-700': 0x6b4a2b,
  'shirt-500': 0x4f86c6,
  'denim-700': 0x3b4c6b,
  'white': 0xffffff,
} as const;

export const S = {
  'color-bg-paper': 0xf4ecd8,
  'color-bg-paper-raised': 0xfbf7ec,
  'color-border-paper': 0xe9dec3,
  'color-text': 0x2b2a33,
  'color-text-muted': 0x4a4852,
  'color-hairline': 0x6e6b78,
  'color-accent': 0xc9963b,
  'color-accent-strong': 0xe07b39,
  'color-focus': 0x2e6fb0,
  'color-danger': 0xc8322b,
  'color-stamina': 0x6daa3f,
  'color-stamina-low': 0xe07b39,
  'color-shadow': 0x2e3153,
  'color-canvas-bg': 0x7fc1ec,
  'color-selection': 0xbfe1f5,
} as const;

export type PrimitiveKey = keyof typeof P;
export type SemanticKey = keyof typeof S;

export function hexString(n: number): string {
  return '#' + n.toString(16).padStart(6, '0');
}
