// Generates src/ui/tokens.css and src/game/palette.ts from design/tokens.json.
// design/tokens.json is the single source of colour, motion, and spacing truth.
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';

const tokens = JSON.parse(readFileSync('design/tokens.json', 'utf8'));
const prim = tokens.primitive;

function resolve(value) {
  const m = /^\{(.+)\}$/.exec(value);
  if (!m) return value;
  if (!(m[1] in prim)) throw new Error(`unknown primitive ${m[1]}`);
  return prim[m[1]];
}

let css = '/* GENERATED by scripts/build-tokens.mjs from design/tokens.json. Do not edit. */\n:root {\n';
for (const [k, v] of Object.entries(prim)) css += `  --${k}: ${v};\n`;
for (const [k, v] of Object.entries(tokens.semantic)) css += `  --${k}: var(--${v.slice(1, -1)});\n`;
for (const [k, v] of Object.entries(tokens.motion)) css += `  --${k}: ${v};\n`;
for (const [k, v] of Object.entries(tokens.space)) css += `  --space-${k}: ${v};\n`;
css += '}\n';
mkdirSync('src/ui', { recursive: true });
writeFileSync('src/ui/tokens.css', css);

const num = (hex) => `0x${hex.slice(1).toLowerCase()}`;
let ts = '// GENERATED by scripts/build-tokens.mjs from design/tokens.json. Do not edit.\n';
ts += 'export const P = {\n';
for (const [k, v] of Object.entries(prim)) ts += `  '${k}': ${num(v)},\n`;
ts += '} as const;\n\nexport const S = {\n';
for (const [k, v] of Object.entries(tokens.semantic)) ts += `  '${k}': ${num(resolve(v))},\n`;
ts += '} as const;\n\n';
ts += 'export type PrimitiveKey = keyof typeof P;\nexport type SemanticKey = keyof typeof S;\n\n';
ts += "export function hexString(n: number): string {\n  return '#' + n.toString(16).padStart(6, '0');\n}\n";
mkdirSync('src/game', { recursive: true });
writeFileSync('src/game/palette.ts', ts);
console.log('tokens built: src/ui/tokens.css, src/game/palette.ts');
